{-# OPTIONS -fno-warn-incomplete-patterns #-}
module Printgrammar where

-- pretty-printer generated by the BNF converter

import Absgrammar
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Progr where
  prt i e = case e of
   Program progrhead block -> prPrec i 0 (concatD [prt 0 progrhead , prt 0 block , doc (showString ".")])


instance Print ProgrHead where
  prt i e = case e of
   ProgramHeading id -> prPrec i 0 (concatD [doc (showString "program") , prt 0 id , doc (showString ";")])


instance Print Block where
  prt i e = case e of
   PBlock decpart stms -> prPrec i 0 (concatD [prt 0 decpart , doc (showString "begin") , prt 0 stms , doc (showString "end")])


instance Print DecPart where
  prt i e = case e of
   DeclPart vardecs fundecs -> prPrec i 0 (concatD [prt 0 vardecs , prt 0 fundecs])


instance Print VarDec where
  prt i e = case e of
   VarDecl id type' -> prPrec i 0 (concatD [doc (showString "var") , prt 0 id , doc (showString ":") , prt 0 type'])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print ValDec where
  prt i e = case e of
   ValDecl id type' -> prPrec i 0 (concatD [prt 0 id , doc (showString ":") , prt 0 type'])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print FunDec where
  prt i e = case e of
   FunDecl funhead block -> prPrec i 0 (concatD [prt 0 funhead , doc (showString ";") , prt 0 block])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print FunHead where
  prt i e = case e of
   FunHeader id vardecs valdecs type' -> prPrec i 0 (concatD [doc (showString "function") , prt 0 id , doc (showString "(") , prt 0 vardecs , prt 0 valdecs , doc (showString ")") , doc (showString ":") , prt 0 type'])


instance Print Type where
  prt i e = case e of
   TInt  -> prPrec i 0 (concatD [doc (showString "integer")])
   TBool  -> prPrec i 0 (concatD [doc (showString "boolean")])
   TArray n type' -> prPrec i 0 (concatD [doc (showString "Array") , doc (showString "[") , prt 0 n , doc (showString "]") , doc (showString "of") , prt 0 type'])
   TRecord valdecs -> prPrec i 0 (concatD [doc (showString "record") , doc (showString "begin") , prt 0 valdecs , doc (showString "end")])
   TFunction types type' -> prPrec i 0 (concatD [doc (showString "lambda") , doc (showString "(") , prt 0 types , doc (showString ")") , prt 0 type'])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Stm where
  prt i e = case e of
   StmBlock stms -> prPrec i 0 (concatD [doc (showString "begin") , prt 0 stms , doc (showString "end")])
   AssignmentStm lval exp -> prPrec i 0 (concatD [prt 0 lval , doc (showString ":=") , prt 0 exp])
   IfStm exp stm0 stm -> prPrec i 0 (concatD [doc (showString "if") , prt 0 exp , doc (showString "then") , prt 0 stm0 , doc (showString "else") , prt 0 stm])
   WhileStm exp stm -> prPrec i 0 (concatD [doc (showString "while") , prt 0 exp , doc (showString "do") , prt 0 stm])
   ForStm stm0 exp stm -> prPrec i 0 (concatD [doc (showString "for") , prt 0 stm0 , doc (showString "to") , prt 0 exp , doc (showString "do") , prt 0 stm])
   PrintStm exp -> prPrec i 0 (concatD [doc (showString "print") , prt 0 exp])
   ReturnStm exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp])
   Skip  -> prPrec i 0 (concatD [doc (showString "skip")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Exp where
  prt i e = case e of
   EEqual exp0 exp -> prPrec i 1 (concatD [prt 2 exp0 , doc (showString "==") , prt 2 exp])
   ENotEqual exp0 exp -> prPrec i 1 (concatD [prt 2 exp0 , doc (showString "!=") , prt 2 exp])
   EGreaterThan exp0 exp -> prPrec i 1 (concatD [prt 2 exp0 , doc (showString ">") , prt 2 exp])
   ELowerThan exp0 exp -> prPrec i 1 (concatD [prt 2 exp0 , doc (showString "<") , prt 2 exp])
   EAnd exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "&&") , prt 3 exp])
   EOr exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "||") , prt 3 exp])
   EAdd exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "+") , prt 3 exp])
   ESub exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "-") , prt 3 exp])
   EMul exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "*") , prt 4 exp])
   EDiv exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "/") , prt 4 exp])
   EInt n -> prPrec i 4 (concatD [prt 0 n])
   EVar lval -> prPrec i 4 (concatD [prt 0 lval])
   EBool boolean -> prPrec i 4 (concatD [prt 0 boolean])
   EFuncCall id exps -> prPrec i 4 (concatD [prt 0 id , doc (showString "(") , prt 0 exps , doc (showString ")")])
   ELambda vardecs valdecs type' block -> prPrec i 4 (concatD [doc (showString "lambda") , doc (showString "(") , prt 0 vardecs , prt 0 valdecs , doc (showString ")") , doc (showString "->") , prt 0 type' , doc (showString ";") , prt 0 block])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print LVal where
  prt i e = case e of
   LValIdent id -> prPrec i 0 (concatD [prt 0 id])
   LValArrayField id exp -> prPrec i 0 (concatD [prt 0 id , doc (showString "[") , prt 0 exp , doc (showString "]")])
   LValRecordField id0 id -> prPrec i 0 (concatD [prt 0 id0 , doc (showString ".") , prt 0 id])


instance Print Boolean where
  prt i e = case e of
   BoolTrue  -> prPrec i 0 (concatD [doc (showString "true")])
   BoolFalse  -> prPrec i 0 (concatD [doc (showString "false")])



